#!/usr/bin/env php
<?php

if (empty($argv[1]) || !is_readable($argv[1])) {
    fwrite(STDERR, 'Usage: ektomm-preview-html campaignconfig.php'.PHP_EOL);
    die(1);
}

// read the config
require($argv[1]);

$tmpfile = tempnam(sys_get_temp_dir(), 'ektomm');
$htmlfile = $tmpfile.'.html';
rename($tmpfile, $htmlfile);
file_put_contents($htmlfile, $config['htmlBody']);
exec('env xdg-open '.escapeshellarg($htmlfile));

